### ISSUE TITLE
计划战斗的素材模式只能进行一次

### ISSUE THREAD

**Issue by September9-iris** [MangetsuC/arkHelper#10]
只是关卡的话能成功进行

**Comment by MangetsuC** [comment]
请您详细描述问题，我测试没有问题

**Comment by September9-iris** [comment]
我在选完打什么素材打多少个之后运行，在第一次打完那个副本之后就停留在”行动结束“界面没有其他操作了，小助手上也是显示“停止虚拟博士”

**Comment by MangetsuC** [comment]
请问您使用的小助手版本，模拟器，模拟器分辨率分别是多少？如果可能的话 请将arkhelper.log文件的最新几行发上来

**Comment by September9-iris** [comment]
2.6.6 ；MuMu模拟器；1920x1080；
[2021-05-27 22:47:40]Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "appQT.py", line 993, in start
  File "foo\arknight\Schedule.py", line 467, in run
  File "foo\arknight\Schedule.py", line 339, in runTimes
  File "foo\pictureR\pictureFind.py", line 97, in matchImg
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-2b5g8ysb\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by MangetsuC** [comment]
我已发现问题，您应该可以通过将其放在没有中文的路径下使其恢复工作

**Comment by September9-iris** [comment]
可以正常运行了 谢谢
