### ISSUE TITLE
无法启动模拟器

### ISSUE THREAD

**Issue by ctj12461** [MangetsuC/arkHelper#12]
如题，点击`启动虚拟博士`没有反应，不会弹出模拟器窗口。  
用的是雷电模拟器  
控制台输出：
```plain
[2021-06-12 11:34:44]error: device not found

[2021-06-12 11:34:44]
[2021-06-12 11:34:44]Exception in thread Thread-53:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "appQT.py", line 991, in start
  File "foo\arknight\Battle.py", line 64, in connect
  File "foo\adb\adbCtrl.py", line 157, in connect
ValueError: invalid literal for int() with base 10: ''
```
`arkHelper`版本：2.6.6

**Comment by ctj12461** [comment]
根据<https://github.com/MangetsuC/arkHelper/issues/4>已找到问题了
