### ISSUE TITLE
进入基建报错

### ISSUE THREAD

**Issue by lastxxx2** [MangetsuC/arkHelper#37]
[2021-11-24 14:42:18]Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "appQT.py", line 983, in start
  File "foo\ui\UILogistic.py", line 275, in run
  File "foo\logisticDepartment\Logistic.py", line 560, in run
  File "foo\logisticDepartment\Logistic.py", line 94, in enterLogisticPanel
  File "foo\ocr\ocr.py", line 35, in getText
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lastxxx2** [comment]
应该是我依赖没装全
