### ISSUE TITLE
雷电模拟器无法使用

### ISSUE THREAD

**Issue by HellSakura** [MangetsuC/arkHelper#4]
```
[2020-08-23 21:25:09]127.0.0.1:5555
[2020-08-23 21:25:29]127.0.0.1:62026
[2020-08-23 21:25:31]127.0.0.1:5555
[2020-08-23 21:26:02]* daemon not running. starting it now on port 5037 *
* daemon started successfully *
connected to 127.0.0.1:5555

[2020-08-23 21:26:02]error: device offline

[2020-08-23 21:26:02]
[2020-08-23 21:26:03]Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "appQT.py", line 667, in start
  File "foo\arknight\Battle.py", line 47, in connect
  File "foo\adb\adbCtrl.py", line 91, in connect
ValueError: invalid literal for int() with base 10: ''
```
应该是在获取屏幕尺寸的时候出错，但是`device offline`错误似乎和adb的版本有关
***
我将arkhelper中自带的adb替换为airtest的adb后，可以正常获取到屏幕尺寸，但是似乎传过来的截图无法打开
但是如果使用airtest进行截图的话是正常显示的
```
[2020-08-23 22:09:34]already connected to 127.0.0.1:5555

[2020-08-23 22:09:38]Physicalsize:1280x720
[2020-08-23 22:09:41]Exception in thread Thread-22:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "appQT.py", line 669, in start
  File "foo\arknight\Schedule.py", line 332, in run
  File "foo\arknight\Schedule.py", line 71, in goLevel
  File "foo\adb\adbCtrl.py", line 125, in screenShot
  File "site-packages\PIL\Image.py", line 2818, in open
OSError: cannot identify image file 'D:/python/arkhelper/bin/adb/arktemp.png'
```

**Comment by MangetsuC** [comment]
### 请尝试用arkhelper中自带的：adb.exe、AdbWinApi.dll、AdbWinUsbApi.dll替换雷电模拟器目录下的这三个文件。
但这样做应该会导致一些原本依赖雷电模拟器重新封装的adb独有命令的程序失效
似乎是雷电模拟器重新封装的adb导致了端口的占用，也有可能是adb版本不同导致的，很抱歉，我目前也没有找到更好的解决方法

**Comment by MangetsuC** [comment]
至于疑似截图无法打开的问题，实际上是PIL读取图片失败（arkhelper会将截取的图片一律转为分辨率1440*810进行处理）
arkhelper截取图片部分代码如下
```python
self.cmd.run('adb -s {device} exec-out screencap -p > {0}/{1}.png'\.format(self.adbPath, pngName, device = self.ip))
pic0 = open(self.adbPath + '/' + pngName +'.png', 'br')
bys = pic0.read().replace(b'\r\n', b'\n')
pic0.close()
pic1 = open(self.adbPath + '/' + pngName +'.png', 'bw')   
pic1.write(bys)
pic1.close()
```
可能是airtest的adb有做修改，其获得的文件的格式PIL不支持，也可能是在将`\r\n`重新替换为`\n`这一过程中带来的错误

**Comment by HellSakura** [comment]
多次尝试后仍然无法读取图片
换用mumu模拟器后正常使用，弃用雷电

**Comment by MangetsuC** [comment]
经过测试，雷电模拟器使用小助手需要按以下步骤进行操作：
1. 结束所有adb进程，可以切换到小助手adb目录下（/bin/adb)执行`adb kill-server`
2. 在小助手目录下，执行`adb start-server`或`adb devices`（实际上其它启动adb的命令均可）
3. 运行雷电模拟器
4. 打开小助手
* 注：3、4步的顺序无所谓
鉴于步骤较为复杂，不推荐一般用户使用雷电模拟器配合小助手
