### ISSUE TITLE
雷电模拟器无法使用

### ISSUE THREAD

**Issue by Nokia-1208** [MangetsuC/arkHelper#6]
```
[2021-01-31 17:59:13]127.0.0.1:5555
[2021-01-31 17:59:24]connected to 127.0.0.1:5555

[2021-01-31 17:59:24]error: device offline

[2021-01-31 17:59:24]
[2021-01-31 17:59:24]Exception in thread [2021-01-31 17:59:24]Thread-2[2021-01-31 17:59:24]:
[2021-01-31 17:59:24]Traceback (most recent call last):
[2021-01-31 17:59:24]  File "threading.py", line 932, in _bootstrap_inner
[2021-01-31 17:59:24]  File "threading.py", line 870, in run
[2021-01-31 17:59:24]  File "appQT.py", line 803, in start
[2021-01-31 17:59:24]  File "foo\arknight\Battle.py", line 47, in connect
[2021-01-31 17:59:24]  File "foo\adb\adbCtrl.py", line 105, in connect
[2021-01-31 17:59:24]ValueError[2021-01-31 17:59:24]: [2021-01-31 17:59:24]invalid literal for int() with base 10: ''
[2021-01-31 17:59:24]Exception in threading.excepthook:
[2021-01-31 17:59:24]Exception ignored in thread started by[2021-01-31 17:59:24]: [2021-01-31 17:59:24]<bound method Thread._bootstrap of <Thread(Thread-2, started daemon 12716)>>
[2021-01-31 17:59:24]Traceback (most recent call last):
[2021-01-31 17:59:24]  File "threading.py", line 890, in _bootstrap
[2021-01-31 17:59:24]  File "threading.py", line 934, in _bootstrap_inner
[2021-01-31 17:59:24]  File "threading.py", line 1212, in invoke_excepthook
[2021-01-31 17:59:24]AttributeError[2021-01-31 17:59:24]: [2021-01-31 17:59:24]'EmittingStr' object has no attribute 'flush'
[2021-01-31 17:59:24]Exception ignored in sys.unraisablehook[2021-01-31 17:59:24]: [2021-01-31 17:59:24]<built-in function unraisablehook>
[2021-01-31 17:59:24]AttributeError[2021-01-31 17:59:24]: [2021-01-31 17:59:24]'EmittingStr' object has no attribute 'flush'
```

**Comment by HellSakura** [comment]
参考 #4
